CREATE TABLE proveedor(
id_proveedor NUMBER,
nombre VARCHAR2(100),
direccion VARCHAR2(200),
paginaweb VARCHAR2(100),
telefono VARCHAR2(8)

);


CREATE TABLE producto(
Proveedor_id_proveedor NUMBER,
PRODUCTO_ID NUMBER,
sku INTEGER,
nombre VARCHAR2(30),
precio FLOAT(2),
stock NUMBER, 
id NUMBER
);

CREATE TABLE VENTA(
CLIENTE_CLIENTE_ID NUMBER,
PRODUCTO_PRODUCTO_ID NUMBER, 
sku INTEGER, 
cui VARCHAR2(13),
id INTEGER, 
fecha DATE,
monto FLOAT(2)
);


CREATE TABLE CATEGORIA(
CATEGORIA_ID NUMBER,
id INTEGER,
nombre VARCHAR2(20),
descripcion VARCHAR2(40)
);

CREATE TABLE CLIENTE(
CLIENTE_ID NUMBER,
cui VARCHAR2(13),
nit VARCHAR2(10),
nombre VARCHAR2(100),
direccion VARCHAR2(200)
);

CREATE TABLE TELEFONO(
CLIENTE_CLIENTE_ID NUMBER,
cui VARCHAR2(13),
id INTEGER,
telefono VARCHAR2(8)
);
